### ISSUE TITLE
Vertical BarElements return NaN

### ISSUE THREAD

**Issue by SerGlushko** [BriefFiniteElementNet/BriefFiniteElement.Net#96]
**Describe the bug**
Greetings! First of all, thank you for your continued development and support of this fantastic library. I've been using BFE.NET version from autumn 2019 in my project and decided to migrate to the newest build. I have encountered an issue: any 2D frame or truss I create have NaN values of support reactions, internal forces and deformations for the vertical elements, e.g BarElement (0, 0, 0), (0, 0, 1).
This issue might also effect FrameElement2Node elements.

**To Reproduce**
This is the code We've used and caused wrong result/ runtime error

```
var m1 = new Model();

m1.Nodes.Add(new Node(0, 0, 0) { Label = "n1" });

m1.Nodes.Add(new Node(0, 0, 6) { Label = "n2" });

m1.Nodes["n1"].Constraints = new Constraint(dx: DofConstraint.Fixed, dy: DofConstraint.Fixed, dz: DofConstraint.Fixed, rx: DofConstraint.Fixed, ry: DofConstraint.Fixed, rz: DofConstraint.Fixed);

m1.Nodes["n2"].Loads.Add(new NodalLoad(new Force(0, 0, -4000, 0, 0, 0)));

m1.Elements.Add(new BarElement(m1.Nodes["n1"], m1.Nodes["n2"]) { Label = "r1" });

(m1.Elements["r1"] as BarElement).Behavior = BarElementBehaviours.FullFrame;

(m1.Elements["r1"] as BarElement).Section = new BriefFiniteElementNet.Sections.UniformParametric1DSection(16.43 / 10000, 541.22 / 100000000, 44.92 / 100000000, 541.22 / 100000000 + 44.92 / 100000000);

(m1.Elements["r1"] as BarElement).Material = BriefFiniteElementNet.Materials.UniformIsotropicMaterial.CreateFromYoungPoisson(210 * Math.Pow(10, 9), 0.3);

m1.Solve();

var r11 = m1.Nodes[0].GetSupportReaction();

var r12 = m1.Nodes[1].GetSupportReaction();

Console.WriteLine("n0 reaction: {0}", r11);

Console.WriteLine("n1 reaction: {0}", r12);

Console.ReadKey();
```

![image](https://user-images.githubusercontent.com/22731503/98684321-14ae9c00-2377-11eb-86c5-a85a899c5ecc.png)

![image](https://user-images.githubusercontent.com/22731503/98685843-efbb2880-2378-11eb-8d8b-419d89f3a32a.png)

**Expected behavior**
The expected result for n0 is "F: 0, 0, 4000, M: 0, 0, 0"

**Additional context**
![image](https://user-images.githubusercontent.com/22731503/98685065-fbf2b600-2377-11eb-9363-cf68c2339eba.png)

I've tested multiple frame configurations and ones without strictly vertical elements had correct results.

**Comment by epsi1on** [comment]
I think there is problem with transformation calculations
I'll check this week and fix the issue.
Thanks

**Comment by epsi1on** [comment]
Hi
This works fine now. this is the result of your code
I did not changed the code.
![image](https://user-images.githubusercontent.com/7839141/99980581-a24dab00-2dbd-11eb-8706-a51a18eb7ab1.png)

**Comment by SerGlushko** [comment]
Hello, I've downloaded the latest version of the library, results remain the same for me

![image](https://user-images.githubusercontent.com/22731503/100335367-f509ab80-2fe5-11eb-869c-05df5f3cbb40.png)

**Comment by epsi1on** [comment]
Could you please also check with `model.Solve_MPC()` instead of `model.Solve()`?
I've coppied your code into this file:
https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/7ab78543b48b2f50fd1942dba29f686033e5dd3e/BriefFiniteElementNet.Validation/GithubIssues/Issue96.cs#L10

If you set `BriefFiniteElementNet.TestConsole.csproj` as startup project, it will call

https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/blob/7ab78543b48b2f50fd1942dba29f686033e5dd3e/BriefFiniteElementNet.TestConsole/Program.cs#L39

Could you please check?

**Comment by SerGlushko** [comment]
I've tested Solve_MPC method, it returns NaN. Same for the project in the TestConsole
![image](https://user-images.githubusercontent.com/22731503/100421961-6dca3f80-309a-11eb-8fd3-5d2d66d6c7be.png)

Here's the matrix:
<details>
  <summary>Click to expand</summary>
  595673076.923077,0,84134615.3846154,0,0,0,-588942307.692308,252403846.153846,-33653846.1538462,0,0,0,6730769.23076923,-252403846.153846,50480769.2307692,0,0,0,-13461538.4615385,0,-100961538.461538,0,0,0;0,175000000,0,0,0,0,168269230.769231,-168269230.769231,33653846.1538462,0,0,0,-168269230.769231,6730769.23076923,-33653846.1538462,0,0,0,0,-13461538.4615385,0,0,0,0;84134615.3846154,0,191826923.076923,0,0,0,-50480769.2307693,50480769.2307693,-168269230.769231,0,0,0,33653846.1538462,-50480769.2307693,23557692.3076923,0,0,0,-67307692.3076923,0,-47115384.6153846,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;-588942307.692308,168269230.769231,-50480769.2307692,0,0,0,757211538.461539,-420673076.923077,0,0,0,0,-168269230.769231,252403846.153846,-50480769.2307692,0,0,0,0,0,100961538.461538,0,0,0;252403846.153846,-168269230.769231,50480769.2307692,0,0,0,-420673076.923077,757211538.461539,0,0,0,0,168269230.769231,-588942307.692308,50480769.2307692,0,0,0,0,0,-100961538.461538,0,0,0;-33653846.1538462,33653846.1538462,-168269230.769231,0,0,0,0,0,336538461.538462,0,0,0,-33653846.1538462,33653846.1538462,-168269230.769231,0,0,0,67307692.3076923,-67307692.3076923,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;6730769.23076923,-168269230.769231,33653846.1538462,0,0,0,-168269230.769231,168269230.769231,-33653846.1538462,0,0,0,175000000,0,0,0,0,0,-13461538.4615385,0,0,0,0,0;-252403846.153846,6730769.23076923,-50480769.2307692,0,0,0,252403846.153846,-588942307.692308,33653846.1538462,0,0,0,0,595673076.923077,-84134615.3846154,0,0,0,0,-13461538.4615385,100961538.461538,0,0,0;50480769.2307693,-33653846.1538462,23557692.3076923,0,0,0,-50480769.2307693,50480769.2307693,-168269230.769231,0,0,0,0,-84134615.3846154,191826923.076923,0,0,0,0,67307692.3076923,-47115384.6153846,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;-13461538.4615385,0,-67307692.3076923,0,0,0,0,0,67307692.3076923,0,0,0,-13461538.4615385,0,0,0,0,0,26923076.9230769,0,0,0,0,0;0,-13461538.4615385,0,0,0,0,0,0,-67307692.3076923,0,0,0,0,-13461538.4615385,67307692.3076923,0,0,0,0,26923076.9230769,0,0,0,0;-100961538.461539,0,-47115384.6153846,0,0,0,100961538.461539,-100961538.461539,0,0,0,0,0,100961538.461539,-47115384.6153846,0,0,0,0,0,94230769.2307693,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;
</details>

**Comment by epsi1on** [comment]
There was problem with bar transformation which is fixed.
Could you please do check again?
Thanks

**Comment by SerGlushko** [comment]
The example works correctly now, but I've tried the latest version in my main project that uses some legacy code too. The issue is still there for FrameElement2Node elements

**Comment by epsi1on** [comment]
it should be fixed, could you please do check again?

**Comment by SerGlushko** [comment]
It works for FrameElement2Node now too.
Thank you!
